#!/usr/bin/env python3
"""
Test script for AI analysis functionality.

This script tests the AI analysis pipeline without requiring a full network capture.
It creates mock data and verifies that the export and analysis functions work correctly.
"""

import os
import sys
import json
from pathlib import Path

# Add net_watch to path
sys.path.insert(0, str(Path(__file__).parent))

from net_watch.ai_analysis import ScanResultsExporter, AIPatternAnalyzer, AIAnalysisEngine
from net_watch.alerts import AlertManager, Alert, AlertLevel
from net_watch.tracking.device_tracker import DeviceTracker
from net_watch.tracking.domain_tracker import DomainTracker
from net_watch.tracking.connection_tracker import ConnectionTracker
from net_watch.tracking.session_tracker import SessionTracker


class MockCapture:
    """Mock capture object for testing."""
    def __init__(self):
        self.total_time = 120.5
        self.packet_count = 1543


class MockMonitor:
    """Mock NetworkMonitor for testing export functionality."""

    def __init__(self):
        self.alert_manager = AlertManager()
        self.device_tracker = DeviceTracker()
        self.domain_tracker = DomainTracker()
        self.connection_tracker = ConnectionTracker()
        self.session_tracker = SessionTracker()
        self.capture = MockCapture()

        # Add some mock data
        self._populate_mock_data()

    def _populate_mock_data(self):
        """Create realistic mock data for testing."""
        import time
        current_time = time.time()

        # Mock device
        device_ip = "192.168.1.100"
        self.device_tracker.track_dns_query(device_ip, "example.com")
        self.device_tracker.track_http_request(device_ip, "example.com")
        self.device_tracker.track_connection(device_ip, "93.184.216.34", 443, 1024)

        # Mock suspicious domains
        suspicious_domains = [
            "api-analytics.suspicious-tracker.com",
            "x8j3k2m9q1z7.net",  # High entropy (DGA-like)
            "c2-server.evil.com",
        ]

        for domain in suspicious_domains:
            for i in range(10):
                timestamp = current_time - (60 * (10 - i))  # Every 60 seconds
                self.domain_tracker.track_dns_query(domain, device_ip, timestamp)

        # Mock connections
        self.connection_tracker.track_connection(device_ip, "93.184.216.34", 443, success=True)
        self.connection_tracker.track_connection(device_ip, "10.0.0.50", 22, success=False)

        # Port scanning pattern
        for port in range(20, 35):
            self.connection_tracker.track_connection(device_ip, "10.0.0.50", port, success=False)

        # Mock alerts
        self.alert_manager.add_alert(Alert(
            level=AlertLevel.ALERT,
            message=f"Device {device_ip} contacted suspicious-tracker.com every 60 seconds",
            explanation="Behavior matches automated beaconing patterns. Could be legitimate service or malware C2.",
            technical_details="Query count: 10, Interval: 60.0s"
        ))

        self.alert_manager.add_alert(Alert(
            level=AlertLevel.WARNING,
            message=f"High entropy domain detected: x8j3k2m9q1z7.net",
            explanation="Domain name has high randomness (Shannon entropy 4.2). May be generated by DGA malware.",
            technical_details="Entropy: 4.2, Threshold: 4.0"
        ))

        self.alert_manager.add_alert(Alert(
            level=AlertLevel.ALERT,
            message=f"Port scanning detected from {device_ip}",
            explanation=f"Device attempted connections to 15 different ports on 10.0.0.50",
            technical_details="Ports: 20-34, Duration: 2 seconds"
        ))


def test_export():
    """Test JSON export functionality."""
    print("=" * 60)
    print("TEST 1: Scan Results Export")
    print("=" * 60)

    monitor = MockMonitor()
    exporter = ScanResultsExporter(output_dir="./test_scan_results")

    try:
        json_file = exporter.export_to_json(monitor, filename="test_export.json")
        print(f"✓ Export successful: {json_file}")

        # Verify file exists and is valid JSON
        with open(json_file, 'r') as f:
            data = json.load(f)

        print(f"✓ JSON file valid")
        print(f"  - Alerts: {len(data['alerts'])}")
        print(f"  - Devices: {len(data['devices'])}")
        print(f"  - Domains: {len(data['domains'])}")
        print(f"  - Connections: {data['connections']['total_connections']}")

        return json_file

    except Exception as e:
        print(f"✗ Export failed: {e}")
        import traceback
        traceback.print_exc()
        return None


def test_ai_analysis(json_file):
    """Test AI analysis functionality."""
    print("\n" + "=" * 60)
    print("TEST 2: AI Analysis")
    print("=" * 60)

    # Check for API key
    api_key = os.getenv('ANTHROPIC_API_KEY')
    if not api_key:
        print("✗ ANTHROPIC_API_KEY not set")
        print("  Set it with: export ANTHROPIC_API_KEY='your-key-here'")
        print("  Skipping AI analysis test...")
        return False

    try:
        analyzer = AIPatternAnalyzer(api_key=api_key)
        print("✓ AI analyzer initialized")

        print("  Calling Claude API (this may take 10-30 seconds)...")
        results = analyzer.analyze_scan_results(json_file)

        print("✓ AI analysis completed")
        print("\n" + "-" * 60)
        print("AI ANALYSIS PREVIEW (first 500 chars):")
        print("-" * 60)
        preview = results['ai_analysis'][:500]
        print(preview)
        if len(results['ai_analysis']) > 500:
            print(f"... ({len(results['ai_analysis']) - 500} more characters)")
        print("-" * 60)

        return True

    except ImportError:
        print("✗ anthropic package not installed")
        print("  Install with: pip install anthropic")
        return False
    except Exception as e:
        print(f"✗ AI analysis failed: {e}")
        import traceback
        traceback.print_exc()
        return False


def test_full_pipeline():
    """Test the complete AI analysis pipeline."""
    print("\n" + "=" * 60)
    print("TEST 3: Full Pipeline (Export + Analysis + Report)")
    print("=" * 60)

    api_key = os.getenv('ANTHROPIC_API_KEY')
    if not api_key:
        print("✗ ANTHROPIC_API_KEY not set - skipping full pipeline test")
        return False

    try:
        monitor = MockMonitor()
        engine = AIAnalysisEngine(output_dir="./test_scan_results", api_key=api_key)

        print("  Running full analysis pipeline...")
        results = engine.run_full_analysis(monitor, save_report=True)

        print("✓ Full pipeline completed")
        print(f"  - Scan data: {results['scan_file']}")
        print(f"  - Report: {results['report_file']}")

        # Verify report file exists
        report_path = Path(results['report_file'])
        if report_path.exists():
            print(f"✓ Report file created ({report_path.stat().st_size} bytes)")
        else:
            print(f"✗ Report file not found")
            return False

        return True

    except Exception as e:
        print(f"✗ Full pipeline failed: {e}")
        import traceback
        traceback.print_exc()
        return False


def cleanup():
    """Clean up test files."""
    print("\n" + "=" * 60)
    print("CLEANUP")
    print("=" * 60)

    test_dir = Path("./test_scan_results")
    if test_dir.exists():
        import shutil
        shutil.rmtree(test_dir)
        print("✓ Test directory removed")
    else:
        print("  No cleanup needed")


def main():
    """Run all tests."""
    print("\n" + "=" * 60)
    print("AI ANALYSIS TEST SUITE")
    print("=" * 60)

    # Test 1: Export
    json_file = test_export()
    if not json_file:
        print("\n✗ Export test failed - stopping")
        return 1

    # Test 2: AI Analysis (optional - requires API key)
    ai_success = test_ai_analysis(json_file)

    # Test 3: Full Pipeline (optional - requires API key)
    if ai_success:
        pipeline_success = test_full_pipeline()
    else:
        print("\nSkipping full pipeline test (no API key)")
        pipeline_success = False

    # Cleanup
    cleanup()

    # Summary
    print("\n" + "=" * 60)
    print("TEST SUMMARY")
    print("=" * 60)
    print(f"Export:          {'✓ PASS' if json_file else '✗ FAIL'}")
    print(f"AI Analysis:     {'✓ PASS' if ai_success else '○ SKIP (no API key)'}")
    print(f"Full Pipeline:   {'✓ PASS' if pipeline_success else '○ SKIP (no API key)'}")
    print("=" * 60)

    if json_file and (not os.getenv('ANTHROPIC_API_KEY')):
        print("\nℹ  To test AI features, set ANTHROPIC_API_KEY and run again")

    return 0 if json_file else 1


if __name__ == '__main__':
    sys.exit(main())
